name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      run: |
        ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
         with:
           ruby-version: 3.1 # Change this to your Ruby version

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build Nanoc site
      run: |
         nanoc
         nanoc view

   
