name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 1.1.3 # Change this to your Ruby version

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build Nanoc site
      run: |
         nanoc
         nanoc view

   
